/**
 * @fileoverview Update command — rescan prompts and rebuild command map.
 *
 * When called from the CLI, this command:
 * 1. Verifies `_bmad/` exists
 * 2. Scans `.github/prompts/` and `.github/agents/` for official BMAD files
 * 3. Scans manifest CSV files for command counts
 * 4. Writes a sentinel file to trigger VS Code extension rescan
 * 5. Prints a summary of discovered commands
 *
 * This command does NOT mirror, convert, or rewrite prompt files.
 * It reads only official files generated by `npx bmad-method install`.
 *
 * @module cli/update
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

/* ------------------------------------------------------------------ */
/*  Types                                                             */
/* ------------------------------------------------------------------ */

export interface UpdateOptions {
  /** Working directory (project root). */
  cwd: string;
}

/* ------------------------------------------------------------------ */
/*  Pretty output helpers                                             */
/* ------------------------------------------------------------------ */

const FMT = {
  green: (s: string) => `\x1b[32m${s}\x1b[0m`,
  red: (s: string) => `\x1b[31m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  cyan: (s: string) => `\x1b[36m${s}\x1b[0m`,
  bold: (s: string) => `\x1b[1m${s}\x1b[0m`,
  dim: (s: string) => `\x1b[2m${s}\x1b[0m`,
};

/* ------------------------------------------------------------------ */
/*  Update command                                                    */
/* ------------------------------------------------------------------ */

export async function update(options: UpdateOptions): Promise<void> {
  const { cwd } = options;

  console.log('');
  console.log(FMT.bold('  BMAD Copilot Adapter — Update'));
  console.log(FMT.dim('  ─────────────────────────────'));
  console.log('');

  // ── 1. Verify _bmad/ exists ─────────────────────────────────
  const bmadDir = path.join(cwd, '_bmad');
  if (!fs.existsSync(bmadDir)) {
    console.log(`  ${FMT.red('✖')} No _bmad/ directory found in ${cwd}`);
    console.log('');
    console.log(FMT.dim('  Run: npx bmad-copilot-adapter bootstrap'));
    process.exit(1);
  }
  console.log(`  ${FMT.green('✔')} Found _bmad/ directory`);

  // ── 2. Scan .github/prompts/ ────────────────────────────────
  const promptsDir = path.join(cwd, '.github', 'prompts');
  const agentsDir = path.join(cwd, '.github', 'agents');

  let promptCount = 0;
  let agentCount = 0;

  if (fs.existsSync(promptsDir)) {
    try {
      const files = fs.readdirSync(promptsDir).filter(
        (f) => f.startsWith('bmad') && f.endsWith('.prompt.md'),
      );
      promptCount = files.length;
    } catch { /* ignore */ }
  }

  if (fs.existsSync(agentsDir)) {
    try {
      const files = fs.readdirSync(agentsDir).filter(
        (f) => f.startsWith('bmad') && f.endsWith('.agent.md'),
      );
      agentCount = files.length;
    } catch { /* ignore */ }
  }

  if (promptCount > 0 || agentCount > 0) {
    console.log(`  ${FMT.green('✔')} Found ${promptCount} prompt file(s), ${agentCount} agent file(s)`);
  } else {
    console.log(`  ${FMT.yellow('◇')} No Copilot prompt files found in .github/`);
  }

  // ── 3. Scan manifest CSV files for command count ─────────────
  const configDir = path.join(bmadDir, '_config');
  let helpEntryCount = 0;
  let manifestAgentCount = 0;
  let taskCount = 0;
  let toolCount = 0;

  if (fs.existsSync(configDir)) {
    helpEntryCount = countCsvRows(path.join(configDir, 'bmad-help.csv'));
    manifestAgentCount = countCsvRows(path.join(configDir, 'agent-manifest.csv'));
    taskCount = countCsvRows(path.join(configDir, 'task-manifest.csv'));
    toolCount = countCsvRows(path.join(configDir, 'tool-manifest.csv'));
  }

  // ── 4. Detect installed modules ──────────────────────────────
  const modules = detectModules(bmadDir);

  // ── 5. Write update sentinel for extension pickup ────────────
  //    The extension watches _bmad/ for changes, so touching a
  //    sentinel file triggers its debounced rescan.
  const sentinelPath = path.join(bmadDir, '.copilot-update');
  try {
    fs.writeFileSync(sentinelPath, new Date().toISOString(), 'utf8');
    console.log(`  ${FMT.green('✔')} Wrote update sentinel for VS Code extension`);
  } catch {
    console.log(`  ${FMT.yellow('◇')} Could not write update sentinel (non-critical)`);
  }

  // ── 6. Print summary ────────────────────────────────────────
  console.log('');
  console.log(FMT.dim('  ─────────────────────────────'));
  console.log(`  ${FMT.green('✔')} ${FMT.bold('Update complete')}`);
  console.log('');
  console.log(`  Modules:       ${modules.length > 0 ? modules.join(', ') : 'none'}`);
  console.log(`  Help entries:  ${helpEntryCount}`);
  console.log(`  Agents:        ${manifestAgentCount}`);
  console.log(`  Tasks:         ${taskCount}`);
  console.log(`  Tools:         ${toolCount}`);
  console.log(`  Prompt files:  ${promptCount}`);
  console.log(`  Agent files:   ${agentCount}`);
  console.log('');

  if (promptCount === 0 && agentCount === 0) {
    console.log(FMT.yellow('  ⚠ No Copilot prompt files found.'));
    console.log(FMT.dim('    Run: npx bmad-method install --tools github-copilot --yes'));
  } else {
    console.log(FMT.dim('  Reload VS Code window or use @bmad /update to apply changes.'));
  }
  console.log('');
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                           */
/* ------------------------------------------------------------------ */

/**
 * Count non-header rows in a CSV file.
 */
function countCsvRows(filePath: string): number {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split('\n').filter((l) => l.trim() && !l.startsWith('#'));
    return Math.max(0, lines.length - 1); // Minus header row
  } catch {
    return 0;
  }
}

/**
 * Detect installed module directories under `_bmad/`.
 */
function detectModules(bmadDir: string): string[] {
  try {
    return fs
      .readdirSync(bmadDir, { withFileTypes: true })
      .filter(
        (e) =>
          e.isDirectory() &&
          e.name !== '_config' &&
          e.name !== '_memory' &&
          e.name !== 'docs' &&
          e.name !== 'ide' &&
          !e.name.startsWith('.'),
      )
      .map((e) => e.name);
  } catch {
    return [];
  }
}
