/**
 * @fileoverview Prompt Mirror — DEPRECATED historical module.
 *
 * @deprecated **This module is retained for reference only.** The adapter
 * is a pure read-only bridge and does NOT mirror, convert, or generate
 * prompt files. The official `npx bmad-method install --tools github-copilot`
 * is the sole source of truth for `.github/prompts/` and `.github/agents/`.
 *
 * No active code imports this module. It will be removed in a future version.
 *
 * --- Original description ---
 *
 * When a workspace has BMAD installed with `--tools claude-code` but
 * **not** `--tools github-copilot`, the `.github/prompts/` and
 * `.github/agents/` directories will be missing.
 *
 * This module reads the official prompt files generated by the
 * claude-code tool under `_bmad/ide/claude-code/` and mirrors them
 * into the GitHub Copilot locations with **minimal transformation**:
 *
 * 1. Filename colons (`:`) → dashes (`-`).
 * 2. Frontmatter `command:` field → `name:` field (colons → dashes).
 * 3. Body content is **never modified**.
 *
 * The mirrored files are standard `.prompt.md` / `.agent.md` that the
 * Copilot prompt executor can consume directly.
 *
 * @module promptMirror
 */

import * as fs from 'node:fs/promises';
import * as fsSync from 'node:fs';
import * as path from 'node:path';

/* ------------------------------------------------------------------ */
/*  Public types                                                      */
/* ------------------------------------------------------------------ */

/** Result returned by {@link ensureCopilotPrompts}. */
export interface MirrorResult {
  /** Whether mirroring was actually performed. */
  performed: boolean;
  /** `true` if Copilot prompt files already existed (mirror skipped). */
  alreadyExists: boolean;
  /** Number of `.prompt.md` files written. */
  promptCount: number;
  /** Number of `.agent.md` files written. */
  agentCount: number;
  /** Number of files skipped (already existed at destination). */
  skippedCount: number;
  /** Source directory used (absolute path), or `null` if not found. */
  sourceDir: string | null;
  /** Destination base directory (`.github/`), or `null`. */
  destDir: string | null;
  /** Human-readable summary message. */
  message: string;
}

/** Parameters for {@link ensureCopilotPrompts}. */
export interface MirrorParams {
  /** Absolute path to the workspace root. */
  workspaceRoot: string;
  /** Absolute path to the `_bmad` directory. */
  bmadDir: string;
}

/* ------------------------------------------------------------------ */
/*  Main entry point                                                  */
/* ------------------------------------------------------------------ */

/**
 * Ensure that GitHub Copilot prompt files exist in the workspace.
 *
 * **Logic:**
 * 1. If `.github/prompts/` already contains `bmad*.prompt.md` files
 *    → skip (return `alreadyExists: true`).
 * 2. Look for `_bmad/ide/claude-code/prompts/` as mirror source.
 * 3. Copy each file with minimal transformation.
 * 4. Repeat for `_bmad/ide/claude-code/agents/` → `.github/agents/`.
 *
 * @param params - Workspace and BMAD directory paths.
 * @returns Mirror result with counts and status message.
 */
export async function ensureCopilotPrompts(
  params: MirrorParams,
): Promise<MirrorResult> {
  const { workspaceRoot, bmadDir } = params;

  // ── 1. Check if Copilot prompt files already exist ──────────
  const copilotPromptsDir = path.join(workspaceRoot, '.github', 'prompts');
  if (hasBmadPromptFiles(copilotPromptsDir)) {
    return {
      performed: false,
      alreadyExists: true,
      promptCount: 0,
      agentCount: 0,
      skippedCount: 0,
      sourceDir: null,
      destDir: null,
      message: 'GitHub Copilot prompt files already exist — mirror skipped.',
    };
  }

  // ── 2. Locate claude-code source directories ────────────────
  const claudeCodeBase = path.join(bmadDir, 'ide', 'claude-code');
  const srcPromptsDir = path.join(claudeCodeBase, 'prompts');
  const srcAgentsDir = path.join(claudeCodeBase, 'agents');

  const hasPromptSource = fsSync.existsSync(srcPromptsDir);
  const hasAgentSource = fsSync.existsSync(srcAgentsDir);

  if (!hasPromptSource) {
    return {
      performed: false,
      alreadyExists: false,
      promptCount: 0,
      agentCount: 0,
      skippedCount: 0,
      sourceDir: null,
      destDir: null,
      message:
        'GitHub Copilot prompt files not found and claude-code prompts missing.\n' +
        'Install BMAD with claude-code tool:\n' +
        '  npx bmad-method install --modules bmm --tools claude-code --yes',
    };
  }

  // ── 3. Mirror prompts ───────────────────────────────────────
  const destPromptsDir = copilotPromptsDir;
  const destAgentsDir = path.join(workspaceRoot, '.github', 'agents');

  let promptCount = 0;
  let agentCount = 0;
  let skippedCount = 0;

  // 3a. Mirror *.prompt.md files
  const promptResults = await mirrorDirectory(
    srcPromptsDir,
    destPromptsDir,
    '.prompt.md',
  );
  promptCount = promptResults.written;
  skippedCount += promptResults.skipped;

  // 3b. Mirror *.agent.md files (optional — may not exist)
  if (hasAgentSource) {
    const agentResults = await mirrorDirectory(
      srcAgentsDir,
      destAgentsDir,
      '.agent.md',
    );
    agentCount = agentResults.written;
    skippedCount += agentResults.skipped;
  }

  const total = promptCount + agentCount;
  const message = total > 0
    ? `Mirror complete: ${promptCount} prompt(s), ${agentCount} agent(s) mirrored from claude-code.`
    : `Mirror found source files but wrote 0 new files (${skippedCount} already existed).`;

  return {
    performed: total > 0,
    alreadyExists: false,
    promptCount,
    agentCount,
    skippedCount,
    sourceDir: claudeCodeBase,
    destDir: path.join(workspaceRoot, '.github'),
    message,
  };
}

/* ------------------------------------------------------------------ */
/*  Directory mirroring                                               */
/* ------------------------------------------------------------------ */

/**
 * Mirror all matching files from `srcDir` to `destDir` with minimal
 * transformation.
 *
 * @param srcDir   - Source directory (e.g. `_bmad/ide/claude-code/prompts/`).
 * @param destDir  - Destination directory (e.g. `.github/prompts/`).
 * @param suffix   - File suffix filter (e.g. `.prompt.md`).
 * @returns Counts of written and skipped files.
 */
async function mirrorDirectory(
  srcDir: string,
  destDir: string,
  suffix: string,
): Promise<{ written: number; skipped: number }> {
  let written = 0;
  let skipped = 0;

  if (!fsSync.existsSync(srcDir)) {
    return { written, skipped };
  }

  const entries = await fs.readdir(srcDir);
  const matchingFiles = entries.filter((f) => f.endsWith(suffix));

  if (matchingFiles.length === 0) {
    return { written, skipped };
  }

  // Ensure destination directory exists
  await fs.mkdir(destDir, { recursive: true });

  for (const srcFile of matchingFiles) {
    const destFileName = sanitiseFileName(srcFile);
    const destPath = path.join(destDir, destFileName);

    // Never overwrite existing user files
    if (fsSync.existsSync(destPath)) {
      skipped++;
      continue;
    }

    const srcPath = path.join(srcDir, srcFile);
    const content = await fs.readFile(srcPath, 'utf8');
    const transformed = transformContent(content);

    await fs.writeFile(destPath, transformed, 'utf8');
    written++;
  }

  return { written, skipped };
}

/* ------------------------------------------------------------------ */
/*  Content transformation (minimal)                                  */
/* ------------------------------------------------------------------ */

/**
 * Apply minimal frontmatter transformation to prompt file content.
 *
 * **Rules:**
 * - If frontmatter has `command: bmad:bmm:create-prd` → add/replace
 *   with `name: bmad-bmm-create-prd` (colons → dashes).
 * - If frontmatter already has `name:` → keep as-is.
 * - Body content is **never modified**.
 *
 * @param raw - Raw file content (UTF-8).
 * @returns Transformed content.
 */
function transformContent(raw: string): string {
  const fmMatch = raw.match(/^(---\r?\n)([\s\S]*?\r?\n)(---\r?\n)([\s\S]*)$/);
  if (!fmMatch) {
    // No frontmatter — return as-is
    return raw;
  }

  const fmOpen = fmMatch[1];   // "---\n"
  let fmBody = fmMatch[2];     // frontmatter fields
  const fmClose = fmMatch[3];  // "---\n"
  const body = fmMatch[4];     // everything after frontmatter

  // Check if `name:` already exists
  if (/^name\s*:/m.test(fmBody)) {
    // Already has a name field — no transformation needed
    return raw;
  }

  // Check for `command:` field and convert to `name:`
  const commandMatch = fmBody.match(/^(command\s*:\s*)(.+)$/m);
  if (commandMatch) {
    const commandValue = commandMatch[2].trim();
    // Convert colon-style to dash-style: bmad:bmm:create-prd → bmad-bmm-create-prd
    const nameValue = commandValue.replaceAll(':', '-');
    // Replace `command:` line with `name:` line
    fmBody = fmBody.replace(
      commandMatch[0],
      `name: ${nameValue}`,
    );
  }

  return fmOpen + fmBody + fmClose + body;
}

/* ------------------------------------------------------------------ */
/*  Filename sanitisation                                             */
/* ------------------------------------------------------------------ */

/**
 * Sanitise a filename for cross-platform compatibility.
 *
 * Converts colons (used in BMAD CLI syntax) to dashes.
 * Example: `bmad:bmm:create-prd.prompt.md` → `bmad-bmm-create-prd.prompt.md`
 *
 * @param name - Original filename.
 * @returns Sanitised filename safe for Windows/macOS/Linux.
 */
function sanitiseFileName(name: string): string {
  return name.replaceAll(':', '-');
}

/* ------------------------------------------------------------------ */
/*  Detection helpers                                                 */
/* ------------------------------------------------------------------ */

/**
 * Check whether a directory contains at least one `bmad*.prompt.md` file.
 *
 * @param dir - Absolute path to the directory.
 * @returns `true` if BMAD Copilot prompt files are present.
 */
function hasBmadPromptFiles(dir: string): boolean {
  if (!fsSync.existsSync(dir)) {
    return false;
  }
  try {
    const files = fsSync.readdirSync(dir);
    return files.some((f) => f.startsWith('bmad') && f.endsWith('.prompt.md'));
  } catch {
    return false;
  }
}

/**
 * Check whether claude-code prompt source files exist under `_bmad/`.
 *
 * @param bmadDir - Absolute path to the `_bmad` directory.
 * @returns `true` if `_bmad/ide/claude-code/prompts/` contains files.
 */
export function hasClaudeCodeSource(bmadDir: string): boolean {
  const srcDir = path.join(bmadDir, 'ide', 'claude-code', 'prompts');
  if (!fsSync.existsSync(srcDir)) {
    return false;
  }
  try {
    const files = fsSync.readdirSync(srcDir);
    return files.some((f) => f.endsWith('.prompt.md'));
  } catch {
    return false;
  }
}
